language: python
python:
  - "2.7"
install:
  - pip install jsonschema
script:
  - wget https://raw.githubusercontent.com/TUSB/minecraft-json-schemas/master/scripts/validate_check.py
  - chmod +x validate_check.py
  - python ./validate_check.py
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
