title: "<ここにタイトルを入力>"
labels: [アイデア]
body: 
- type: markdown
  attributes:
    value: |
      ## 新しいアイデアの提案ありがとうございます。
      以下の質問に答えていただくと、採用しやすくなります。
      赤い印がついているものは必ず答えてください。
- type: dropdown
  id: category
  attributes:
    label: アイデアのカテゴリー
    options:
      - 島・エリア・建築物
      - ギミック
      - Mob
      - アイテム・TUSBメモリー
      - 刻印
      - 交易
      - 釣り・報酬・ドロップアイテム
      - レシピ
      - 職業スキル
      - インターフェイス全般
      - TIPS
      - 進捗
      - チュートリアル
- type: textarea
  id: idea
  attributes:
    label: アイデア概要
    description: |
      新しいアイデアについての説明を記入する。  
      画像のアップロードも可能です。
  validations:
    required: true
- type: textarea
  id: why
  attributes:
    label: アイデアの要望理由
    description: |
      なぜこのアイデアを要望するのか？  
  validations:
    required: true
- type: textarea
  id: realization
  attributes:
    label: 実現方法
    description: どのようにアイデアを実現するかを記入する。
    placeholder: |
      1.
      2.
      3.
      ...
- type: markdown
  attributes:
    value: |
      以下は技術的な報告です。

      ---
- type: textarea
  id: use_system
  attributes:
    label: 使用するシステム
    description: アイデアを実現するために使用するシステムを指定する。
- type: textarea
  id: command
  attributes:
    label: コマンド例
    description: 実現するためのコマンド例を記入する。functionと同じように記述することができます。
    render: mcfunction
