name: やるべきリスト
description: TODOとか今後やらないといけないタスク
title: "[TODO] <ここにタイトルを入力>"
labels: [todo]
body:
- type: markdown
  attributes:
    value: |
      ## リリースまでや今後必要になるであろうTODOを記載してください。
      赤い印がついているものは必ず答えてください。
- type: dropdown 
  id: priority
  attributes:
    label: 重要度
    description: |
      このタスクに対しての重要度を記入してください。
      - 低め: コードのリファクタリングや設計思想で気になるなどのやらなくても今回のVerではやらなくてもいいレベル
      - 通常: 今回のバージョンは入れなくても良いが、できたらやったほうがいいよなぁレベル
      - 高い: 動作に不都合(困る)ので、今後のためにも入れておきたいレベル
      - 急いで: 動作に支障出るので、入れておきたいレベル(リリース後でもUpdateで対処できる)
      - 今すぐ: 動作に支障出るので、入れておきたいレベル(リリース後でもUpdateで対処できない、もしくはv13αまでに必須)
    options:
      - 低め
      - 通常
      - 高い
      - 急いで
      - 今すぐ
  validations:
    required: true
- type: dropdown
  id: Version
  attributes:
    label: このTODOはこのUSBv13 Versionに影響が出る
    options:
      - v13α
      - v13.1α
      - v13.2α
      - v13 Release
      - v14 以降
  validations:
    required: false
- type: textarea
  id: task-detail
  attributes:
    label: タスク内容
    description: 何故これが必要なのかタスク内容を箇条書きで記載してください
    placeholder : |
      # TODO/タスク の詳細
      ## 何故必要なのか
      1. 〇〇に`/kill @e` を実行する、コマンドブロックがある
      2.
      3.
      ...
    value : |
      # TODO/タスク の詳細
      <!-- 知らない人から見てもわかりやすく、簡潔に。　短すぎず長すぎず -->
      ## 何故必要なのか
      1. 
      2.
      3.
      ...
  validations:
    required: true

- type: textarea
  id: task-progress
  attributes:
    label: これをしないとどうなるのか予想される問題を記載してください
    description: |
      上記の内容と関連性があるように記載してください。
      深掘りする場合は 1.1. のように段落構成にしてください。
    placeholder : |
      # TODO/タスク の詳細
      ## 何故必要なのか
      1.  `/kill @e` が実行される可能性がある
        1.1. `/kill @e` が実行されるとシステムが停止する。
      2.
      3.
      ...
    value : |
      # TODO/タスク の詳細
      <!-- 知らない人から見てもわかりやすく、簡潔に。　短すぎず長すぎず -->
      ## 何故必要なのか
      1. 
      2.
      3.
      ...
  validations:
    required: true
