name: やるべきリスト
description: TODOとか今後やらないといけないタスク
title: "[TODO] <ここにタイトルを入力>"
labels: [Todo]
body:
- type: markdown
  attributes:
    value: |
      ## リリースまでや今後必要になるであろうTODOを記載してください。
      赤い印がついているものは必ず答えてください。
      基本は1チケット=1タスク原則にしてください。

- type: dropdown 
  id: priority
  attributes:
    label: 重要度
    description: |
      このタスクに対しての重要度を記入してください。**(急いで以上は乱用しないように)**
      - 低め: コードのリファクタリングや設計思想で気になるなどのやらなくても今回のVerではやらなくてもいいレベル
      - 通常: 今回のバージョンは入れなくても良いが、できたらやったほうがいいよなぁレベル
      - 高い: 動作に不都合(困る)ので、今後のためにも入れておきたいレベル
      - **急いで: 動作に支障出るので、入れておきたいレベル(リリース後でもUpdateで対処できる)**
      - ***今すぐ: 動作に支障出るので、入れておきたいレベル(リリース後でもUpdateで対処できない、もしくはv13αまでに必須)***
    options:
      - 低め
      - 通常
      - 高い
      - 急いで
      - 今すぐ
  validations:
    required: true

- type: markdown
  attributes:
    value: |  
     **優先度 通常、低め は完遂義務はありません。**
      ```
       例: この設計思想で開発したいので、データパックを、この形にしたい。 → 低め
       
       例: `/kill @e` を実行するコマンドブロックが存在する。
                ┣ ただし、コマンドブロックはデバッグエリア(一般プレイヤーが触れれない場所)にしかない → 通常
                ┗ ただし、コマンドブロックは通常世界(一般プレイヤーが触れれる場所)にある
                    ┣ ただし、コマンドブロックは特定条件下かつ一般プレイヤーが実行するのは難しい → 高い
                    ┗ ただし、コマンドブロックは一般プレイヤーが実行する可能性がある → 急いで
                        ┗ さらに、データパックのUpdateだけでは、置き換えとかで対処できない → 今すぐ
      ```
      ---
      
- type: dropdown
  id: Version
  attributes:
    label: このTODOはこのTUSB Versionに影響が出る
    options:
      - v13α
      - v13 Release
      - v14 以降
      - その他
      
  validations:
    required: false
- type: textarea
  id: task-detail
  attributes:
    label: タスク内容
    description: 何故これが必要なのかタスク内容を箇条書きで記載してください
    placeholder : |
      ## 何故必要なのか?
      1. 
      2. 
      3.
    value : |
      <!-- 知らない人から見てもわかりやすく、簡潔に。短すぎず長すぎず -->
      ## 何故必要なのか?
      1. 
      2.
      3.

      <!-- ※ ここはコメントアウトされます
      ## 何故必要なのか?
      1. 〇〇に`/kill @e` を実行する、コマンドブロックがある-->
      
  validations:
    required: true

- type: textarea
  id: task-progress
  attributes:
    label: 予想される問題
    description: |
      上記の内容と関連性があるように記載してください。
      深掘りする場合は 1.1. のように段落構成にしてください。
    placeholder : |
      ## 何故必要なのか
      1. 
      2.
      3.
      
    value : |
      <!-- これをしないとどうなるのか予想される問題を記載してください -->
      ## 何故必要なのか
      1. 
      2.
      3.
      
      <!-- ※ ここはコメントアウトされます
      ## 何故必要なのか
      1.  `/kill @e` が実行される可能性がある
        1.1. `/kill @e` が実行されるとシステムが停止する。 -->
        
  validations:
    required: true

- type: textarea
  id: task-priority
  attributes:
    label: なぜこの重要度にしたのか
    description: |
      なぜこの重要度にしたのかを詳細記載してください。(重要度 高い 以上向け)
    placeholder : |
      <!-- (重要度 高い 以上向け) -->
      ## 何故この重要度なのか
      1. 
      2. 
      3. 

      ## いつまで対応が必要か
      1. 
      2. 
      3. 

    value: |
      ## 何故この重要度なのか
      1. 
      2. 
      3. 
      
      ## いつまで対応が必要か
      1. 
      2. 
      3. 
      
      <!-- ※ ここはコメントアウトされます
      ## 何故この重要度なのか
      1. コマンドブロックは通常世界にある(座標: x,y,z)
      2. コマンドブロックは一般プレイヤーが実行する可能性がある
        2.2. RS流せば実行可能
      3.  周りに水流で作成した建築物があり、コマンドで置き換えすると建築物が崩れる可能性が高い。

      その為、重要度は`急いで` を適用しました。

      ## いつまで対応が必要か
      1. World崩壊引き起こすのでTUSB v13α のリリースまでに必須 -->
      
  validations:
    required: false
