# kics-scan disable=555ab8f9-2001-455e-a077-f2d0f41e2fb9
---
name: PR Code Review

on:
  pull_request:
    types:
      - ready_for_review
      - synchronize
  issue_comment:
    types:
      - created

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    if:
      >
      (
        (github.event_name == 'issue_comment' && github.event.comment.body == '/review')
        ||
        ( ! github.event.pull_request.merged && ! startsWith(github.event.pull_request.title, 'Merge') )
      )
    runs-on: ubuntu-latest
    steps:
      - uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LANGUAGE: Japanese
          OPENAI_API_ENDPOINT: https://api.openai.com/v1
          MODEL: o1-mini
          top_p: 1
          temperature: 1
          MAX_PATCH_LENGTH: 10000
          IGNORE_PATTERNS: ./*,*.md
          PROMPT:
            |
            あなたはMinecraft配布ワールド『The Unusual SkyBlock』の専属AIコードレビュワーとして、以下のルールに従ってPRレビューをしてください。
            1. コード規約・ディレクトリ構成・データ管理ルールを統一し、誤字などを指摘していき、開発規模が拡大しても整合性を維持できるようにする。  
            2. MOBのHP、職業スキル、デバフ・ギミック、エリア設計といったゲームバランス要素を共通指針でまとめ、プレイヤーに適切な難易度・プレイフィールを提供する。
            3. 職業レベルやエンチャント・アイテム管理などの詳細ルールも含め、制作時の混乱を防ぐ。
