name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test:
    # if: ${{ contains(github.event.*.labels.*.name, 'gpt review') }} # Optional; to run only when a label is attached
    runs-on: ubuntu-latest
    steps:
      - uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # Optional
          LANGUAGE: Japanese
          OPENAI_API_ENDPOINT: https://api.openai.com/v1
          # MODEL: chatgpt-4o-latest # https://platform.openai.com/docs/models
          MODEL: o1-mini
          PROMPT: |
            Request: perform PR review mcfuntion code for Minecraft 1.21.1
            Role:Respond as code reviewer for Minecraft distribution world “The Unusual SkyBlock”.
            Regulation: keep brief to point, 50-300 words or less, Markdown format.
            Rule:
            . Avoid halcyonation provide reliable information.
            . do not copy answers, use original content.
            . review code in Minecraft 1.21.1
            Review Refine:
            . check quality readability code
            . Evaluate impact proposed changes on existing functionality.
            . identify security performance concerns
            . identify potential impact on gameplay aware of changes affect gameplay.
            Reference:
            - Repository: [The Unusual SkyBlock](https://github.com/TUSB/TheUnusualSkyBlock)
            - Documentation.
              - [GitHub Wiki](https://github.com/TUSB/TheUnusualSkyBlock/wiki/Top)
              - [Seesaawiki](https://seesaawiki.jp/theunusualskyblock/)
            Run Scenario: respond as code reviewer.
          top_p: 1 # https://platform.openai.com/docs/api-reference/chat/create#chat/create-top_p
          temperature: 1 # https://platform.openai.com/docs/api-reference/chat/create#chat/create-temperature
          max_tokens: 10000
          MAX_PATCH_LENGTH: 10000 # if the patch/diff length is large than MAX_PATCH_LENGTH, will be ignored and won't review. By default, with no MAX_PATCH_LENGTH set, there is also no limit for the patch/diff length.
          IGNORE_PATTERNS: ./*,*.md


# Request: Please perform a PR review of the mcfuntion code for Minecraft 1.21.1.
# Role:Respond as a code reviewer for the Minecraft distribution world “The Unusual SkyBlock”.
# Regulation:Please keep it brief and to the point, 50-300 words or less, in Markdown format.
# Rule: 
# 1. Avoid halcyonation and provide reliable information.
# 2. do not copy other people's answers, but use original content.
# 3. review the code available in Minecraft 1.21.1.
# Review & Refine:
# 1. check the quality and readability of the code 
# 2. Evaluate the impact of the proposed changes on existing functionality. 
# 3. identify any security or performance concerns 
# 4. identify any potential impact on gameplay Be aware of changes that may affect gameplay.
# Reference:
# - Repository: [The Unusual SkyBlock](https://github.com/TUSB/TheUnusualSkyBlock)
# - Documentation.
# - [GitHub Wiki](https://github.com/TUSB/TheUnusualSkyBlock/wiki/Top)
# - [Seesaawiki](https://seesaawiki.jp/theunusualskyblock/)
# Run Scenario: Please respond as a code reviewer.
