name: Lint Check Action
on: push
jobs:
  textlint:
    name: runner / textlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - name: Setup Node/npm
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Exec textlint
        run: |
          git diff origin/${GITHUB_BASE_REF}..origin/${GITHUB_HEAD_REF} \
            --diff-filter=AM \
            --name-only
