---
# kics-scan disable=555ab8f9-2001-455e-a077-f2d0f41e2fb9
name: Close stale issues and PRs
on:
  schedule:
    - cron: 0 15 * * *
  workflow_dispatch: null
permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message:
            |
            > [!WARNING]
            > このissueを最後に更新してから**365日経過**しているため、古くなっています。
            >  このまま、何も活動の更新がないと**30日後**にこのissueはクローズされます。
            > クローズを防ぐにはコメント更新するか`古くなった`ラベルを削除してください。
          stale-pr-message:
            |
            > [!WARNING]
            > このPRは**180日間活動がない**ため、古くなっています。
            > このまま、何も活動の更新がないと**14日後**にこのPRはクローズされます。
            > クローズを防ぐにはコメント更新するか`古くなった`ラベルを削除してください。
          close-issue-message:
            |
            > [!IMPORTANT]
            > このissueは、**14日間**何の活動もなく停滞していたため、クローズされました。
          close-pr-message:
            |
            > [!IMPORTANT]
            > このPRは、10日間何の活動もなく停滞しているため、クローズされました。
          days-before-issue-stale: 365
          days-before-pr-stale: 180
          days-before-issue-close: 30
          days-before-pr-close: 14
          stale-issue-label: 古くなった
          close-pr-label: 自動クローズ
          close-issue-label: 自動クローズ
          close-issue-reason: not_planned
          include-only-assigned: true
          exempt-draft-pr: true
          exempt-issue-labels: "担当募集, 優先度: 高い, リリース予定"
