---
name: lint-datapack
on:
  push: null
  pull_request: null
  workflow_dispatch: null
permissions:
  contents: read
jobs:
  fix-lint-issues:
    permissions:
      contents: write
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Super-Linter
        uses: super-linter/super-linter@v7.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # ACTIONS_RUNNER_DEBUG: true
          DEFAULT_BRANCH: 1-21-1-dev
          OUTPUT_FORMAT: tap
          OUTPUT_DETAILS: detailed
          DISABLE_ERRORS: false
          VALIDATE_ALL_CODEBASE: true
          ENABLE_GITHUB_ACTIONS_STEP_SUMMARY: true
          IGNORE_GITIGNORED_FILES: true
          IGNORE_GENERATED_FILES: true
          FIX_ANSIBLE: true
          FIX_CLANG_FORMAT: true
          FIX_CSHARP: true
          FIX_CSS: true
          FIX_DOTNET_SLN_FORMAT_ANALYZERS: true
          FIX_DOTNET_SLN_FORMAT_STYLE: true
          FIX_ENV: true
          FIX_GO_MODULES: true
          FIX_GO: true
          FIX_GOOGLE_JAVA_FORMAT: true
          FIX_GROOVY: true
          FIX_JAVASCRIPT_ES: true
          FIX_JAVASCRIPT_PRETTIER: true
          FIX_JAVASCRIPT_STANDARD: true
          FIX_JSON: true
          FIX_JSONC: true
          FIX_JSX: true
          FIX_JUPYTER_NBQA_BLACK: true
          FIX_JUPYTER_NBQA_ISORT: true
          FIX_JUPYTER_NBQA_RUFF: true
          FIX_MARKDOWN: true
          FIX_POWERSHELL: true
          FIX_PROTOBUF: true
          FIX_PYTHON_BLACK: true
          FIX_PYTHON_ISORT: true
          FIX_PYTHON_PYINK: true
          FIX_PYTHON_RUFF: true
          FIX_RUBY: true
          FIX_RUST_2015: true
          FIX_RUST_2018: true
          FIX_RUST_2021: true
          FIX_RUST_CLIPPY: true
          FIX_SCALAFMT: true
          FIX_SHELL_SHFMT: true
          FIX_SNAKEMAKE_SNAKEFMT: true
          FIX_SQLFLUFF: true
          FIX_TERRAFORM_FMT: true
          FIX_TSX: true
          FIX_TYPESCRIPT_ES: true
          FIX_TYPESCRIPT_PRETTIER: true
          FIX_TYPESCRIPT_STANDARD: true
      - name: Commit and push linting fixes
        if: always()
        # Run only on:
        # - Pull requests
        # - Not on the default branch
        # if: >
        #   github.event_name == 'pull_request' &&
        #   github.ref_name != github.event.repository.default_branch
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ github.event.pull_request.head.ref || github.head_ref || github.ref }}
          commit_message: NO-ISSUE Fix linting issues
          commit_user_name: super-linter
          commit_user_email: super-linter@super-linter.dev
# jobs:
#   lint:
#     name: lint
#     runs-on: ubuntu-latest
#     steps:
#       - name: checkout repository
#         uses: actions/checkout@v4
#         with:
#           fetch-depth: 0
#       # https://github.com/ChenCMD/datapack-linter
#       - name: lint
#         uses: ChenCMD/datapack-linter@v2
#         with:
#           GITHUB_TOKEN: ${{ github.token }}
