---
# kics-scan disable=555ab8f9-2001-455e-a077-f2d0f41e2fb9
name: Server Notice and Deploy Action
on:
  workflow_dispatch: null
permissions:
  contents: read
  issues: write
  pull-requests: write
jobs:
  notice:
    name: notice mcrcon
    runs-on: ubuntu-latest
    steps:
      - name: Public IP
        id: ip
        uses: haythem/public-ip@v1.2

      - name: Print Public IP
        run:
          |
          echo "${{ steps.ip.outputs.ipv4 }}"
          echo "${{ steps.ip.outputs.ipv6 }}"

      - uses: actions/checkout@v4
      - name: Add Firewalld IP Address
        id: FIREWALL
        env:
          VULTR_API_KEY: ${{ secrets.VULTR_API_KEY }}
          VULTR_FIREWALL_GROUP_ID: ${{ secrets.VULTR_FIREWALL_GROUP_ID }}
          TUSB_SERVER_RCON_PORT: ${{ secrets.TUSB_SERVER_RCON_PORT }}
        run:
          |
          echo "::add-mask::${VULTR_API_KEY}"
          echo "::add-mask::${VULTR_FIREWALL_GROUP_ID}"
          echo "::add-mask::${TUSB_SERVER_RCON_PORT}"
          ADD_FIREWALL="$(curl "https://api.vultr.com/v2/firewalls/${VULTR_FIREWALL_GROUP_ID}/rules" \
            -X POST \
            -H "Authorization: Bearer ${VULTR_API_KEY}" \
            -H "Content-Type: application/json" \
            --data "{
              \"ip_type\": \"v4\",
              \"protocol\": \"tcp\",
              \"port\": \"${TUSB_SERVER_RCON_PORT}\",
              \"subnet\": \"${{ steps.ip.outputs.ipv4 }}\",
              \"subnet_size\": 32,
              \"source\": \"\",
              \"notes\": \"GitHub Action Firewall Rule on Rcon Port\"
            }"
          )"
          echo "ADD_FIREWALL=$ADD_FIREWALL"
          firewall_id="$(echo "$ADD_FIREWALL" | jq -r '.firewall_rule.id')"
          echo "ID=$firewall_id" >> "$GITHUB_OUTPUT"
          echo "firewall_id=$firewall_id"

      - name: Set outputs
        id: vars
        run:
          |
          sha_short="$(git rev-parse --short HEAD)"
          echo "sha_short=$sha_short" >> "$GITHUB_OUTPUT"

      - name: Check outputs
        run: echo "${{ steps.vars.outputs.sha_short }}"

      - name: Install mcrcon
        run:
          |
          wget "https://github.com/Tiiffi/mcrcon/releases/download/v0.7.1/mcrcon-0.7.1-linux-x86-64.tar.gz"
          tar -zxvf mcrcon-0.7.1-linux-x86-64.tar.gz
          mv mcrcon-0.7.1-linux-x86-64/mcrcon /usr/local/bin/

      - name: Sleep for 45 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: 45s

      - name: Notice Bungeecord
        run:
          |
          /usr/local/bin/mcrcon \
            -H "${{ secrets.TUSB_MINECRAFT_SERVER_REMOTE_HOST_IP }}" \
            -p "${{ secrets.TUSB_SERVER_RCON_PASSWORD }}" \
            -P "${{ secrets.TUSB_SERVER_RCON_PORT }}" \
            -w 5 \
            "alertraw [\"\",{\"text\":\"[INFO] \"},{\"text\":\"リポジトリが更新されました。\",\"bold\":true,\"color\":\"yellow\"},{\"text\":\"(Hash: \"},{\"text\":\"${{ steps.vars.outputs.sha_short }}\",\"italic\":true,\"underlined\":true,\"clickEvent\":{\"action\":\"open_url\",\"value\":\"https://github.com/TUSB/TheUnusualSkyBlock/commit/${{ steps.vars.outputs.sha_short }}\"}},{\"text\":\")\"}]"

      - if: always()
        name: Delete Firewalld IP Address
        env:
          VULTR_API_KEY: ${{ secrets.VULTR_API_KEY }}
          VULTR_FIREWALL_GROUP_ID: ${{ secrets.VULTR_FIREWALL_GROUP_ID }}
        run:
          |
          echo "::add-mask::${VULTR_API_KEY}"
          echo "::add-mask::${VULTR_FIREWALL_GROUP_ID}"

          DELETE_FIREWALL="$(curl "https://api.vultr.com/v2/firewalls/${VULTR_FIREWALL_GROUP_ID}/rules/${{ steps.FIREWALL.outputs.ID }}" \
            -X DELETE \
            -H "Authorization: Bearer ${VULTR_API_KEY}" )"
          echo "$DELETE_FIREWALL"

  deploy:
    name: deploy server
    runs-on: ubuntu-latest
    steps:
      - name: Public IP
        id: ip
        uses: haythem/public-ip@v1.2

      - name: Print Public IP
        run:
          |
          echo "${{ steps.ip.outputs.ipv4 }}"
          echo "${{ steps.ip.outputs.ipv6 }}"

      - uses: actions/checkout@v4
      - name: Add Firewalld IP Address
        id: FIREWALL
        env:
          VULTR_API_KEY: ${{ secrets.VULTR_API_KEY }}
          VULTR_FIREWALL_GROUP_ID: ${{ secrets.VULTR_FIREWALL_GROUP_ID }}
          TUSB_MINECRAFT_SERVER_SSH_PORT: ${{ secrets.TUSB_MINECRAFT_SERVER_SSH_PORT }}
        run:
          |
          echo "::add-mask::${VULTR_API_KEY}"
          echo "::add-mask::${VULTR_FIREWALL_GROUP_ID}"
          ADD_FIREWALL="$(curl "https://api.vultr.com/v2/firewalls/${VULTR_FIREWALL_GROUP_ID}/rules" \
            -X POST \
            -H "Authorization: Bearer ${VULTR_API_KEY}" \
            -H "Content-Type: application/json" \
            --data "{
              \"ip_type\": \"v4\",
              \"protocol\": \"tcp\",
              \"port\": \"${TUSB_MINECRAFT_SERVER_SSH_PORT}\",
              \"subnet\": \"${{ steps.ip.outputs.ipv4 }}\",
              \"subnet_size\": 32,
              \"source\": \"\",
              \"notes\": \"GitHub Action Firewall Rule\"
            }"
          )"

          firewall_id="$(echo "$ADD_FIREWALL" | jq -r '.firewall_rule.id')"
          echo "ID=$firewall_id" >> "$GITHUB_OUTPUT"
          echo "$ADD_FIREWALL"

      - name: Sleep for 45 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: 45s

      - name: Deploy by rsync
        uses: trendyminds/github-actions-rsync@master
        with:
          RSYNC_OPTIONS:
            -avzre "ssh -o 'StrictHostKeyChecking no'" --delete
            --timeout=1200 --exclude=".git/" --exclude=".github/"
            --exclude="*.md" --exclude="*.py"
          RSYNC_SOURCE: /
          RSYNC_TARGET: /home/${{ secrets.TUSB_MINECRAFT_SERVER_REMOTE_USER }}/deploy/${{ github.event.repository.name }}
        env:
          SSH_PRIVATE_KEY: ${{ secrets.TUSB_MINECRAFT_SERVER_PRIVATE_KEY }}
          SSH_USERNAME: ${{ secrets.TUSB_MINECRAFT_SERVER_REMOTE_USER }}
          SSH_HOSTNAME: ${{ secrets.TUSB_MINECRAFT_SERVER_REMOTE_HOST_IP }}

      - if: always()
        name: Delete Firewalld IP Address
        env:
          VULTR_API_KEY: ${{ secrets.VULTR_API_KEY }}
          VULTR_FIREWALL_GROUP_ID: ${{ secrets.VULTR_FIREWALL_GROUP_ID }}
        run:
          |
          DELETE_FIREWALL="$(curl "https://api.vultr.com/v2/firewalls/${VULTR_FIREWALL_GROUP_ID}/rules/${{ steps.FIREWALL.outputs.ID }}" \
            -X DELETE \
            -H "Authorization: Bearer ${VULTR_API_KEY}" )"
          echo "$DELETE_FIREWALL"
