name: Label Issue Based on Priority

on:
  issues:
    types: [opened]
jobs:
  add_label_based_on_priority:
    runs-on: ubuntu-latest
    steps:
      - name: Extract priority and add label
        uses: actions/github-script@v6
        with:
          script: |
            const issueBody = context.payload.issue.body;
            const priorityMatch = issueBody.match(/###\s*\*\*重要度\*\*\s*\n\s*(.*)/);
            if (priorityMatch) {
              const priority = priorityMatch[1].trim();
              let label = '';
              if (priority.includes('低め')) {
                label = '優先度: 低い';
              } else if (priority.includes('通常')) {
                label = '優先度: 通常';
              } else if (priority.includes('高い')) {
                label = '優先度: 高い';
              }
              if (label) {
                await github.rest.issues.addLabels({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.issue.number,
                  labels: [label]
                });
              }
            } else {
              console.log('重要度が見つかりませんでした。');
            }
