name: Label Issue Based on Priority

on:
  issues:
    types: [opened, edited]

env:
  PRIORITY: ""
    
jobs:
  set_env_priority:
    runs-on: ubuntu-latest
    outputs:
      PRIORITY: ${{ steps.extract_priority.outputs.PRIORITY }}
    steps:
      - name: Extract priority and set output
        id: extract_priority
        uses: actions/github-script@v6
        with:
          script: |
            const issueBody = context.payload.issue.body;
            const priorityMatch = issueBody.match(/###\s*重要度\s*\n\s*(.*)/);
            if (priorityMatch) {
              const priority = priorityMatch[1].trim();
              core.setOutput('PRIORITY', priority);
              console.log(`Priority set ${priority}`);
            } else {
              core.setOutput('PRIORITY', '');
            }

  add_label_based_on_priority:
    runs-on: ubuntu-latest
    needs: set_env_priority
    if: ${{ needs.set_env_priority.outputs.PRIORITY != '' }}
    steps:
      - name: Add label based on priority
        uses: actions/github-script@v6
        env:
          PRIORITY: ${{ needs.set_env_priority.outputs.PRIORITY }}
        with:
          script: |
            const priority = process.env.PRIORITY;
            let label = '';
            if (priority.includes('低め')) {
              label = '優先度: 低い';
            } else if (priority.includes('通常')) {
              label = '優先度: 通常';
            } else if (priority.includes('高い')) {
              label = '優先度: 高い';
            }
            if (label) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: [label]
              });
            }
      - name: Check issue priority and clean body
        uses: actions/github-script@v6
        with:
          script: |
            const issue = context.payload.issue;
            const issueNumber = issue.number;
            const issueBody = issue.body;
            const priority = process.env.PRIORITY;
            if (priority !== '高い') {
              // 特定のセクションを削除
              const newBody = issueBody.replace(/###\s*なぜ優先度が高いのか[\s\S]*?(?=###|$)/g, '').trim();
              
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                body: newBody
              });
              console.log('Issue body updated as priority is not "高い".');
            } else {
              console.log('Priority is "高い", no changes made.');
            }

      - name: Validate issue content
        uses: actions/github-script@v6
        with:
          script: |
            const issue = context.payload.issue;
            const issueNumber = issue.number;
            const issueBody = issue.body;
            const priority = process.env.PRIORITY;

            // Extract the "Why is this priority?" section
            const taskPriorityMatch = issueBody.match(/##\s*何故この重要度なのか\s*\n([\s\S]*?)(?=\n##|$)/);
            let taskPriorityContent = '';
            if (taskPriorityMatch) {
              taskPriorityContent = taskPriorityMatch[1].trim();
            }

            // Default content
            const defaultContent = `1. 
            2. 
            3.`;

            // Check if priority is "高い" and the "Why is this priority?" section is default or empty
            if (priority === '高い' && (!taskPriorityContent || taskPriorityContent === defaultContent)) {
              // Close the issue
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                state: 'closed',
                state_reason: 'not_planned'
              });

              // Add a comment
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                body: '優先度が「高い」と選択されていますが、必要な情報が記入されていないため、このIssueはクローズされました。必要な情報を記入して再度作成してください。'
              });

              console.log('Issue closed due to missing required information.');
            } else {
              console.log('Issue validation passed.');
            }
